---
apiVersion: v1
kind: Namespace
metadata:
  name: aws9f
---
#news svc
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc-news
  namespace: aws9f
spec:
  selector:
    web: news-svc
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
#news deploy
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: news-deploy
  namespace: aws9f
spec:
  selector:
    matchLabels:
      web: news-svc
  template:
    metadata: 
      labels:
        web: news-svc
    spec:
      containers:
      - name: newsctn
        image: hub.aws9.pri/aws9/news:1.0
        ports:
          - containerPort: 80   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: dev1-sc